# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oqGOeRLpNdS4S4uyrlS6c1U9pSxsJzDJ
"""

!pip install qrcode pillow

import qrcode

url = "https://vidyashreem46.github.io/profile-website/"

img = qrcode.make(url)
img.save("vidyashree_profile_qr.png")

print("QR code created successfully!")